import { Navbar } from '../Navbar';
import Head from 'next/head'
import styles from './MainLayout.module.css';

export const MainLayout = ({children}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>

     {children}
    </div>
  )
}
